@echo off
del /f /s /q ..\GPUCache
del /f /q ..\locales\am.pak
del /f /q ..\locales\ar.pak
del /f /q ..\locales\bg.pak
del /f /q ..\locales\bn.pak
del /f /q ..\locales\ca.pak
del /f /q ..\locales\cs.pak
del /f /q ..\locales\da.pak
del /f /q ..\locales\de.pak
del /f /q ..\locales\el.pak
del /f /q ..\locales\en-GB.pak
del /f /q ..\locales\es-419.pak
del /f /q ..\locales\es.pak
del /f /q ..\locales\et.pak
del /f /q ..\locales\fa.pak
del /f /q ..\locales\fi.pak
del /f /q ..\locales\fil.pak
del /f /q ..\locales\fr.pak
del /f /q ..\locales\gu.pak
del /f /q ..\locales\he.pak
del /f /q ..\locales\hi.pak
del /f /q ..\locales\hr.pak
del /f /q ..\locales\hu.pak
del /f /q ..\locales\id.pak
del /f /q ..\locales\it.pak
del /f /q ..\locales\ja.pak
del /f /q ..\locales\kn.pak
del /f /q ..\locales\ko.pak
del /f /q ..\locales\lt.pak
del /f /q ..\locales\lv.pak
del /f /q ..\locales\ml.pak
del /f /q ..\locales\mr.pak
del /f /q ..\locales\ms.pak
del /f /q ..\locales\nb.pak
del /f /q ..\locales\nl.pak
del /f /q ..\locales\pl.pak
del /f /q ..\locales\pt-BR.pak
del /f /q ..\locales\pt-PT.pak
del /f /q ..\locales\ro.pak
del /f /q ..\locales\ru.pak
del /f /q ..\locales\sk.pak
del /f /q ..\locales\sl.pak
del /f /q ..\locales\sr.pak
del /f /q ..\locales\sv.pak
del /f /q ..\locales\sw.pak
del /f /q ..\locales\ta.pak
del /f /q ..\locales\te.pak
del /f /q ..\locales\th.pak
del /f /q ..\locales\tr.pak
del /f /q ..\locales\uk.pak
del /f /q ..\locales\vi.pak
del /f /q ..\locales\zh-TW.pak
del /f /q ..\*.pdb
pause

