//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 极简浏览器.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("极简浏览器.Resources.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接中断 的本地化字符串。
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法访问地址 的本地化字符串。
        /// </summary>
        public static string AddressUnreachable {
            get {
                return ResourceManager.GetString("AddressUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接已关闭 的本地化字符串。
        /// </summary>
        public static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问被拒绝 的本地化字符串。
        /// </summary>
        public static string ConnectionRefused {
            get {
                return ResourceManager.GetString("ConnectionRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接已重置 的本地化字符串。
        /// </summary>
        public static string ConnectionReset {
            get {
                return ResourceManager.GetString("ConnectionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应时间过长 的本地化字符串。
        /// </summary>
        public static string ConnectionTimedOut {
            get {
                return ResourceManager.GetString("ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到文件 的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络未连接 的本地化字符串。
        /// </summary>
        public static string InternetDisconnected {
            get {
                return ResourceManager.GetString("InternetDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 URL 地址 的本地化字符串。
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析地址 的本地化字符串。
        /// </summary>
        public static string NameNotResolved {
            get {
                return ResourceManager.GetString("NameNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL 协议错误 的本地化字符串。
        /// </summary>
        public static string SslProtocolError {
            get {
                return ResourceManager.GetString("SslProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL 版本不匹配 的本地化字符串。
        /// </summary>
        public static string SslVersionOrCipherMismatch {
            get {
                return ResourceManager.GetString("SslVersionOrCipherMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重定向次数过多 的本地化字符串。
        /// </summary>
        public static string TooManyRedirects {
            get {
                return ResourceManager.GetString("TooManyRedirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 URL 形式 的本地化字符串。
        /// </summary>
        public static string UnknownUrlScheme {
            get {
                return ResourceManager.GetString("UnknownUrlScheme", resourceCulture);
            }
        }
    }
}
