//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 极简浏览器.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("极简浏览器.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Default theme for Windows Vista/7 的本地化字符串。
        /// </summary>
        internal static string UITheme_Aero_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Aero.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default theme for Windows 8/8.1/10 的本地化字符串。
        /// </summary>
        internal static string UITheme_Aero2_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Aero2.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default theme for Windows 9x series 的本地化字符串。
        /// </summary>
        internal static string UITheme_Classic {
            get {
                return ResourceManager.GetString("UITheme.Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Olive theme for Windows XP 的本地化字符串。
        /// </summary>
        internal static string UITheme_Luna_Homestead {
            get {
                return ResourceManager.GetString("UITheme.Luna.Homestead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silver theme for Windows XP 的本地化字符串。
        /// </summary>
        internal static string UITheme_Luna_Metallic {
            get {
                return ResourceManager.GetString("UITheme.Luna.Metallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default blue theme for Windows XP 的本地化字符串。
        /// </summary>
        internal static string UITheme_Luna_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Luna.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Center theme for Windows XP 的本地化字符串。
        /// </summary>
        internal static string UITheme_Royale_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Royale.NormalColor", resourceCulture);
            }
        }
    }
}
