name: .NET Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        configuration: [2.0D, Release3]

    runs-on: windows-latest

    env:
      Solution_Name: 极简浏览器Cef.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: "6.x"

      - name: Restore NuGet Packages
        run: nuget restore

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Build Solution
        run: MSBuild.exe /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}
          path: ./极简浏览器Cef/bin/${{ matrix.configuration }}/*
